import type { Offer } from "../types";
import { timings } from "../flow/timings";
import type { OfferProvider } from "./OfferProvider";

const photo = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=900&h=560&fit=crop&auto=format&q=80`;

export const MOCK_OFFERS: Offer[] = [
  // GOLD (2)
  {
    id: "pacific-heights-suite",
    title: "Pac Heights Designer Suite",
    neighborhood: "Pacific Heights",
    addressLine: "2440 Pacific Ave",
    photoUrl: photo("1600585154340-be6161a56a0c"),
    source: "Airbnb",
    originalPrice: 480,
    beds: 2,
    baths: 2,
    guests: 4,
    rating: 4.95,
    reviews: 312,
    amenities: ["Self check-in", "Workspace", "Skyline view", "Coffee bar"],
    tier: "gold",
    expectedDiscountPct: 22,
    pros: [
      "Top 5% rated in all of Pac Heights",
      "Owner replies in under 10 min — agent verified live",
      "Walk to Fillmore in 4 min; bus 22 at corner",
      "Last-minute cleaning included in negotiated rate",
    ],
    recentReview: {
      author: "Emma R.",
      text: "Quietest unit I've ever stayed in. Skyline view is real. Lock pad worked first try.",
      rating: 5,
      },
    negotiationHighlight:
      "Agent unlocked a 22% discount by mentioning a 3-night stay + same-week competitor pricing in the Marina.",
    verifiedFlags: ["Photos match", "Pricing verified", "No hidden fees"],
    wifiSpeed: "320 Mbps fiber",
    cancellationPolicy: "Free cancellation up to 48h",
  },
  {
    id: "marina-penthouse",
    title: "Marina Penthouse · Bay View",
    neighborhood: "Marina",
    addressLine: "3275 Marina Blvd",
    photoUrl: photo("1560185007-cde436f6a4d0"),
    source: "Booking.com",
    originalPrice: 495,
    beds: 2,
    baths: 2,
    guests: 4,
    rating: 4.9,
    reviews: 188,
    amenities: ["Roof deck", "Parking", "Pet friendly", "Smart lock"],
    tier: "gold",
    expectedDiscountPct: 20,
    pros: [
      "Panoramic bay view — photos independently verified",
      "Free parking + private roof deck (rare in Marina)",
      "Owner agreed to longer-stay rate during the call",
      "Smart locks → self check-in, any hour",
    ],
    recentReview: {
      author: "Jordan M.",
      text: "The view sells itself. Host called within 5 min when our flight was late.",
      rating: 5,
    },
    negotiationHighlight:
      "Owner matched a competing listing's rate after the agent quoted exact pricing for a similar unit two blocks away.",
    verifiedFlags: ["Photos match", "Pricing verified", "Superhost 3 yrs"],
    wifiSpeed: "260 Mbps",
    cancellationPolicy: "Free cancellation up to 72h",
  },

  // GREEN (5)
  {
    id: "hayes-valley-loft",
    title: "Hayes Valley Sun Loft",
    neighborhood: "Hayes Valley",
    addressLine: "451 Hayes St",
    photoUrl: photo("1493809842364-78817add7ffb"),
    source: "Airbnb",
    originalPrice: 395,
    beds: 1,
    baths: 1,
    guests: 2,
    rating: 4.7,
    reviews: 241,
    amenities: ["Walkable", "Workspace", "Espresso machine"],
    tier: "green",
    expectedDiscountPct: 14,
    pros: [
      "Walk score 98 — coffee, bars, Patricia's Green all on the block",
      "Dedicated workspace + 200 Mbps WiFi (verified)",
      "Sunny morning light from east-facing bay window",
    ],
    recentReview: {
      author: "Priya S.",
      text: "Best workspace I've had in any rental. Coffee shop downstairs is a hazard.",
      rating: 5,
    },
    negotiationHighlight:
      "Agent secured a 14% discount in exchange for an early check-in commitment.",
    verifiedFlags: ["Photos match", "Pricing verified"],
    wifiSpeed: "200 Mbps",
    cancellationPolicy: "Free cancellation up to 48h",
  },
  {
    id: "nob-hill-modern",
    title: "Nob Hill Modern 1BR",
    neighborhood: "Nob Hill",
    addressLine: "1180 Sacramento St",
    photoUrl: photo("1522708323590-d24dbb6b0267"),
    source: "VRBO",
    originalPrice: 410,
    beds: 1,
    baths: 1,
    guests: 2,
    rating: 4.7,
    reviews: 156,
    amenities: ["Gym", "Doorman", "In-unit laundry"],
    tier: "green",
    expectedDiscountPct: 15,
    pros: [
      "24/7 doorman + building gym included",
      "Renovated 2024 — kitchen, bath, flooring",
      "Off the cable-car route → genuinely quiet at night",
    ],
    recentReview: {
      author: "Daniel K.",
      text: "Doorman accepted packages for me. Building feels brand new.",
      rating: 5,
    },
    negotiationHighlight:
      "Agent waived the cleaning fee ($95) by referencing competing Nob Hill rates.",
    verifiedFlags: ["Photos match", "Building inspected"],
    wifiSpeed: "180 Mbps",
    cancellationPolicy: "Free cancellation up to 7 days",
  },
  {
    id: "castro-victorian",
    title: "Castro Victorian Flat",
    neighborhood: "Castro",
    addressLine: "489 Castro St",
    photoUrl: photo("1556909114-f6e7ad7d3136"),
    source: "Airbnb",
    originalPrice: 375,
    beds: 2,
    baths: 1,
    guests: 4,
    rating: 4.6,
    reviews: 423,
    amenities: ["Garden", "Workspace", "Bike storage"],
    tier: "green",
    expectedDiscountPct: 13,
    pros: [
      "Private garden access (rare in Castro)",
      "4-year Superhost with 423 reviews",
      "Walk to Castro nightlife and Mission food in <15 min",
    ],
    recentReview: {
      author: "Sofia V.",
      text: "The garden is everything. Host left a hand-drawn map of the neighborhood.",
      rating: 5,
    },
    negotiationHighlight:
      "Agent pinned a 13% discount by booking back-to-back nights and confirming no pets.",
    verifiedFlags: ["Superhost 4 yrs", "Photos match"],
    wifiSpeed: "150 Mbps",
    cancellationPolicy: "Free cancellation up to 48h",
  },
  {
    id: "mission-loft",
    title: "Mission District Loft",
    neighborhood: "Mission",
    addressLine: "2400 Valencia St",
    photoUrl: photo("1554995207-c18c203602cb"),
    source: "Airbnb",
    originalPrice: 385,
    beds: 1,
    baths: 1,
    guests: 3,
    rating: 4.7,
    reviews: 198,
    amenities: ["Workspace", "Pour-over kit", "Sonos system"],
    tier: "green",
    expectedDiscountPct: 16,
    pros: [
      "Heart of Mission food scene — La Taqueria, Tartine, Bi-Rite all within 5 min",
      "Workspace + pour-over kit + Aeropress",
      "97% rating from solo travelers",
    ],
    recentReview: {
      author: "Alex T.",
      text: "Couldn't move out. Walked to dinner every night. Sonos was a nice touch.",
      rating: 5,
    },
    negotiationHighlight:
      "Agent locked in 16% off by referencing two competing Mission listings under $370.",
    verifiedFlags: ["Photos match", "Pricing verified"],
    wifiSpeed: "220 Mbps",
    cancellationPolicy: "Free cancellation up to 48h",
  },
  {
    id: "soma-modern-studio",
    title: "SoMa Modern Studio",
    neighborhood: "SoMa",
    addressLine: "888 Folsom St",
    photoUrl: photo("1505691938895-1758d7feb511"),
    source: "Booking.com",
    originalPrice: 345,
    beds: 0,
    baths: 1,
    guests: 2,
    rating: 4.5,
    reviews: 287,
    amenities: ["Pool", "Gym", "Same-day cleaning"],
    tier: "green",
    expectedDiscountPct: 12,
    pros: [
      "In-building pool + gym included with stay",
      "5-min walk to Powell BART → 25 min to airport",
      "Cleaning re-done on day-of check-in",
    ],
    recentReview: {
      author: "Maya P.",
      text: "Tiny but everything works. Pool sealed the deal after a hot day walking the city.",
      rating: 4,
    },
    negotiationHighlight:
      "Owner threw in a same-day cleaning after the agent flagged late check-in.",
    verifiedFlags: ["Photos match", "Pricing verified"],
    wifiSpeed: "140 Mbps",
    cancellationPolicy: "Free cancellation up to 24h",
  },

  // NORMAL (3)
  {
    id: "inner-richmond-apt",
    title: "Inner Richmond Apartment",
    neighborhood: "Inner Richmond",
    addressLine: "640 Clement St",
    photoUrl: photo("1502672260266-1c1ef2d93688"),
    source: "VRBO",
    originalPrice: 340,
    beds: 1,
    baths: 1,
    guests: 2,
    rating: 4.1,
    reviews: 89,
    amenities: ["Quiet", "Kitchen"],
    tier: "normal",
    expectedDiscountPct: 8,
    pros: ["Quiet block", "Full kitchen"],
  },
  {
    id: "outer-sunset-cottage",
    title: "Outer Sunset Beach Cottage",
    neighborhood: "Outer Sunset",
    addressLine: "1620 Judah St",
    photoUrl: photo("1484154218962-a197022b5858"),
    source: "Airbnb",
    originalPrice: 360,
    beds: 2,
    baths: 1,
    guests: 4,
    rating: 4.2,
    reviews: 134,
    amenities: ["Beach nearby"],
    tier: "normal",
    expectedDiscountPct: 9,
    pros: ["Walk to Ocean Beach", "Quiet residential"],
  },
  {
    id: "glen-park-1br",
    title: "Glen Park Garden 1BR",
    neighborhood: "Glen Park",
    addressLine: "640 Chenery St",
    photoUrl: photo("1568605114967-8130f3a36994"),
    source: "Booking.com",
    originalPrice: 355,
    beds: 1,
    baths: 1,
    guests: 2,
    rating: 4.0,
    reviews: 67,
    amenities: ["Garden", "Quiet"],
    tier: "normal",
    expectedDiscountPct: 10,
    pros: ["Private garden", "BART nearby"],
  },

  // RED (5)
  {
    id: "tenderloin-studio",
    title: "Tenderloin Compact Studio",
    neighborhood: "Tenderloin",
    addressLine: "240 Eddy St",
    photoUrl: photo("1564013799919-ab600027ffc6"),
    source: "Hostelworld",
    originalPrice: 310,
    beds: 0,
    baths: 1,
    guests: 1,
    rating: 3.4,
    reviews: 42,
    amenities: ["WiFi"],
    tier: "red",
    expectedDiscountPct: 2,
    pros: ["Cheap", "Central"],
  },
  {
    id: "sunset-garage",
    title: "Sunset Garage Conversion",
    neighborhood: "Sunset",
    addressLine: "2210 Noriega St",
    photoUrl: photo("1512917774080-9991f1c4c750"),
    source: "VRBO",
    originalPrice: 420,
    beds: 1,
    baths: 1,
    guests: 2,
    rating: 3.6,
    reviews: 31,
    amenities: [],
    tier: "red",
    expectedDiscountPct: 4,
    pros: ["Private entrance"],
  },
  {
    id: "bayview-duplex",
    title: "Bayview Duplex Unit",
    neighborhood: "Bayview",
    addressLine: "1530 Quesada Ave",
    photoUrl: photo("1583847268964-b28dc8f51f92"),
    source: "Booking.com",
    originalPrice: 385,
    beds: 2,
    baths: 1,
    guests: 4,
    rating: 3.5,
    reviews: 28,
    amenities: [],
    tier: "red",
    expectedDiscountPct: 3,
    pros: ["Space"],
  },
  {
    id: "excelsior-basement",
    title: "Excelsior Basement Suite",
    neighborhood: "Excelsior",
    addressLine: "62 Russia Ave",
    photoUrl: photo("1600596542815-ffad4c1539a9"),
    source: "Hostelworld",
    originalPrice: 345,
    beds: 1,
    baths: 1,
    guests: 2,
    rating: 3.4,
    reviews: 19,
    amenities: ["WiFi"],
    tier: "red",
    expectedDiscountPct: 3,
    pros: ["Cheap"],
  },
  {
    id: "mission-bay-pod",
    title: "Mission Bay Tiny Pod",
    neighborhood: "Mission Bay",
    addressLine: "650 Mission Bay Blvd",
    photoUrl: photo("1582268611958-ebfd161ef9cf"),
    source: "Airbnb",
    originalPrice: 375,
    beds: 0,
    baths: 1,
    guests: 1,
    rating: 3.7,
    reviews: 56,
    amenities: ["Gym"],
    tier: "red",
    expectedDiscountPct: 5,
    pros: ["New build"],
  },
];

export const mockOfferProvider: OfferProvider = {
  async *search(_query: string) {
    for (const offer of MOCK_OFFERS) {
      await new Promise<void>((r) =>
        setTimeout(r, timings.researchPerCardStagger),
      );
      yield offer;
    }
  },
};
