import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

/**
 * MSW browser worker.
 *
 * Bootstrapped from `main.tsx` only when `config.USE_MSW === true` (see
 * spec §6). `onUnhandledRequest: 'bypass'` is the critical knob: deleting
 * a handler falls through to the real network, enabling per-endpoint
 * incremental backend swap without code changes elsewhere.
 *
 * `mockServiceWorker.js` is generated by `pnpm msw:init` and committed
 * under `public/` — the path here resolves against the dev server root.
 */
export const worker = setupWorker(...handlers);

export function startWorker(): Promise<ServiceWorkerRegistration | undefined> {
  return worker.start({
    onUnhandledRequest: 'bypass',
    serviceWorker: { url: '/mockServiceWorker.js' },
  });
}
